<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Riok.Mapperly" />
    <ProjectReference Include="..\HJ.Server.Contracts\HJ.Server.Contracts.csproj" />
    <ProjectReference Include="..\HJ.Server.Domain\HJ.Server.Domain.csproj" />
  </ItemGroup>

</Project>