// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace HJ.Server.Infrastructure.Persistence.Optimized
{
    public partial class HJDbContextModel
    {
        private HJDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("5c5b8e65-6da8-4b81-9bde-57b4e09882d6"), entityTypeCount: 9)
        {
        }

        partial void Initialize()
        {
            var installation = InstallationEntityType.Create(this);
            var installationEnvironment = InstallationEnvironmentEntityType.Create(this);
            var applicationLog = ApplicationLogEntityType.Create(this);
            var operation = OperationEntityType.Create(this);
            var operationExecution = OperationExecutionEntityType.Create(this);
            var product = ProductEntityType.Create(this);
            var productVersion = ProductVersionEntityType.Create(this);
            var telemetryEvent = TelemetryEventEntityType.Create(this);
            var tenant = TenantEntityType.Create(this);

            InstallationEnvironmentEntityType.CreateForeignKey1(installationEnvironment, installation);
            OperationExecutionEntityType.CreateForeignKey1(operationExecution, operation);
            ProductVersionEntityType.CreateForeignKey1(productVersion, product);

            InstallationEntityType.CreateAnnotations(installation);
            InstallationEnvironmentEntityType.CreateAnnotations(installationEnvironment);
            ApplicationLogEntityType.CreateAnnotations(applicationLog);
            OperationEntityType.CreateAnnotations(operation);
            OperationExecutionEntityType.CreateAnnotations(operationExecution);
            ProductEntityType.CreateAnnotations(product);
            ProductVersionEntityType.CreateAnnotations(productVersion);
            TelemetryEventEntityType.CreateAnnotations(telemetryEvent);
            TenantEntityType.CreateAnnotations(tenant);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "10.0.10");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
