// <auto-generated />
using HJ.Server.Infrastructure.Persistence;
using HJ.Server.Infrastructure.Persistence.Optimized;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(HJDbContext), typeof(HJDbContextModel))]
